name: Release
on:
  workflow_call:

jobs:
  build:
    name: Upload new project release
    runs-on:
      - macos-latest
    steps:
      - name: Checkout to current repo
        uses: actions/checkout@v3

      - name: Compress EFI to EFI.zip
        run: zip -r -X EFI.zip EFI
        
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@2728235f7dc9ff598bd86ce3c274b74f802d2208
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: EFI.zip
          tag: ${{ github.ref }}
          file_glob: true